/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorRouteImport } from './routes/visitor'
import { Route as HrRouteImport } from './routes/hr'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as ProjectsProjectsIdIndexRouteImport } from './routes/projects/$projectsId/index'

const VisitorRoute = VisitorRouteImport.update({
  id: '/visitor',
  path: '/visitor',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectsIdIndexRoute = ProjectsProjectsIdIndexRouteImport.update({
  id: '/projects/$projectsId/',
  path: '/projects/$projectsId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRoute
  '/hr': typeof HrRoute
  '/visitor': typeof VisitorRoute
  '/blogs': typeof BlogsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectsId': typeof ProjectsProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRoute
  '/hr': typeof HrRoute
  '/visitor': typeof VisitorRoute
  '/blogs': typeof BlogsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectsId': typeof ProjectsProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engineer': typeof EngineerRoute
  '/hr': typeof HrRoute
  '/visitor': typeof VisitorRoute
  '/blogs/': typeof BlogsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectsId/': typeof ProjectsProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engineer'
    | '/hr'
    | '/visitor'
    | '/blogs'
    | '/projects'
    | '/projects/$projectsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/engineer'
    | '/hr'
    | '/visitor'
    | '/blogs'
    | '/projects'
    | '/projects/$projectsId'
  id:
    | '__root__'
    | '/'
    | '/engineer'
    | '/hr'
    | '/visitor'
    | '/blogs/'
    | '/projects/'
    | '/projects/$projectsId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineerRoute: typeof EngineerRoute
  HrRoute: typeof HrRoute
  VisitorRoute: typeof VisitorRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectsIdIndexRoute: typeof ProjectsProjectsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitor': {
      id: '/visitor'
      path: '/visitor'
      fullPath: '/visitor'
      preLoaderRoute: typeof VisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectsId/': {
      id: '/projects/$projectsId/'
      path: '/projects/$projectsId'
      fullPath: '/projects/$projectsId'
      preLoaderRoute: typeof ProjectsProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineerRoute: EngineerRoute,
  HrRoute: HrRoute,
  VisitorRoute: VisitorRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectsIdIndexRoute: ProjectsProjectsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
